### ISSUE TITLE
A module (opencv2) failed to define its name!

### ISSUE THREAD

**Issue by 0xPr0xy** [iauns/cpm#15]
Hi,

The CPM_AddModule command is throwing me the following error:

<code>
CMake Error at cpm-packages/CPM.cmake:1246 (message):
A module (opencv2) failed to define its name!
Call Stack (most recent call first):
CMakeLists.txt:27 (CPM_AddModule)
</code>

This is the definition in my CMakeLists.txt:

<code>
CPM_AddModule("opencv2"
GIT_REPOSITORY "https://github.com/Itseez/opencv"
GIT_TAG "3.0.0"
USE_EXISTING_VER TRUE)
</code>

Is this because opencv2 is not a registered CPM module?
If so, I did submit the repository at cpm rocks, do I need to prepare the repository with a configuration for CPM or is that enough?
If not, please tell me what could be the problem

Thanks

**Comment by ilyas-taouaou** [comment]
Why did you close the issue, how did you solve it?

**Comment by ilyas-taouaou** [comment]
I have the same problem now with SDL with the newer way of using CPM
